### ISSUE TITLE
Mesa panfork appears abandoned

### ISSUE THREAD

**Issue by tidux** [7Ji/orangepi5-archlinuxarm#10]
Did development continue in a new repo?  Did the upstreaming process complete in Mesa but not get imported properly in Arch Linux ARM?  I see that the panfork repo was last committed to in [December](https://gitlab.com/panfork/mesa/-/commits/csf) but the upstream `mesa` package from Arch Linux ARM fails to start Hyprland from tty1.

**Comment by 7Ji** [comment]
> Did development continue in a new repo

No, that repo is where all the development happens

> Did the upstreaming process complete in Mesa but not get imported properly in Arch Linux ARM

No, the official ALARM mesa package stays most up-to-date. I'm not a maintainer of the official ALARM, though, so you better ask upstream.

There is a ongoing PR series on by Alyssa Rosenzweig but they're not merged yet, and the maintainer of panfork doesn't seem to be interested in merging his efforts to upstream.

At least it works for now, and that's it. There's no one both knowledgeable enough about MESA and his fork codebase to help merge the efforts to upstream for now.
