### ISSUE TITLE
error while loading shared libraries: librga.so.2

### ISSUE THREAD

**Issue by Dmitrij-Solovjev** [7Ji/orangepi5-archlinuxarm#14]
My_config
![image](https://github.com/7Ji/orangepi5-archlinuxarm/assets/90474877/9e82c29e-77da-4b14-ac51-c2744966c154)

I also use ```Mali-G610 (Panfrost)```

I have problem with start kodi ```kodi-matrix-mpp-git```.
When i try to start I get an error:
```/usr/lib/kodi/kodi.bin: error while loading shared libraries: librga.so.2: cannot open shared object file: No such file or directory```
after install ```librga-multi-1.9.2-1``` (because """librga```  don't solve problem i've got this:

![msg1603035643-26746](https://github.com/7Ji/orangepi5-archlinuxarm/assets/90474877/1c632851-040e-4fd9-8e6d-213dad3b5fee)

but if i run ```sudo kodi``` video is ok, but don't work sound.
also i can change ````display mode``` to windowed and the problem is gone

**Comment by 7Ji** [comment]
Closed by https://github.com/7Ji-PKGBUILDs/kodi-matrix-mpp-git/commit/ad02b0b46d95ef828f47fedb84b1182c7f3bba0f and https://github.com/7Ji-PKGBUILDs/kodi-nexus-mpp-git/commit/ca7c945f7b752d0fdc8f86bd7ce8829e7bb6cd6a
