### ISSUE TITLE
New `-git` kernel, difference, and how to migrate to it

### ISSUE THREAD

**Issue by wyf9661** [7Ji/orangepi5-archlinuxarm#21]
![图片](https://github.com/7Ji/orangepi5-archlinuxarm/assets/122584107/5b954f7c-96dc-4c7b-a929-a03fab914d35)

**Comment by 7Ji** [comment]
https://github.com/7Ji-PKGBUILDs/.report/issues/5

**Comment by 7Ji** [comment]
Newer images from this repo will come with both kernel packages pre-installed. The one in release has a 5.10.110 in its name but is actually 160, which should be fixed after my builder uploading the new package.

https://github.com/7Ji/orangepi5-archlinuxarm#kernel-selection
