### ISSUE TITLE
Hello 7Ji! I do not understand the command of 'ARM proprietary blob GPU drivers' installation

### ISSUE THREAD

**Issue by DragonSerW** [7Ji/orangepi5-archlinuxarm#31]
I wish to install your distro for my 5B board, and I am confused of the command
```bash
sudo pacman -Syu libmali-valhall-g610-{dummy,gbm,wayland-gbm,x11-gbm,x11-wayland-gbm}
```

I should paste it on terminal as it is or should I write only the `wayland-gbm`?
What does `gbm` mean?

**Comment by 7Ji** [comment]
If you ask, then you should install them all. Because it would be hard to you to tell which exact environment you run in.

GBM: Generic Buffer Management

Basically each of those suffix is for a kind of display target, and GBM ~= console.
