### ISSUE TITLE
My 5B does not boot after pertition resizing @ Debian 12.5.0

### ISSUE THREAD

**Issue by DragonSerW** [7Ji/orangepi5-archlinuxarm#32]
How I resized the partitions: https://geekpeek.net/resize-filesystem-fdisk-resize2fs/.
And how the 5 B goes for now: https://i.ibb.co/k46B9Js/PXL-20240301-180815781.jpg,
https://i.ibb.co/ZhfZqcb/PXL-20240301-180637443.jpg.

**Comment by 7Ji** [comment]
My gut feeling is you've corrupted the kernel image somehow. Reflash, test, then resize, then test. 
And the log, don't take screenshot, send full serial log.
