### ISSUE TITLE
Installation of packages failed due to the error "bsdtar: Failed to set default locale".

### ISSUE THREAD

**Issue by hronro** [7Ji/orangepi5-archlinuxarm#38]
I haven't installed any DE yet, I'm currently using SSH from my MacBook.

When I try to install some packages (especially from the `7Ji` repository), I get this error:

![CleanShot 2024-05-07 at 17 36 57@2x](https://github.com/7Ji/orangepi5-archlinuxarm/assets/15059605/499db22c-e8dc-42fc-9b58-e4bd39cd5a85)

I think I have properly set the locale by following the Arch Linux Installation Guide (https://wiki.archlinux.org/title/Installation_guide):

![CleanShot 2024-05-07 at 17 44 24@2x](https://github.com/7Ji/orangepi5-archlinuxarm/assets/15059605/dc40f181-8bc3-40c3-945f-119f60dc3183)

Any ideas on how to fix this?

**Comment by 7Ji** [comment]
Two things:
- `bsdtar: Failed to set default locale` is not a fatal error, it should not prevent `mkinitcpio` from being finished
- `mkinitcpio` on ALARM is pretty much broken now, I'd recommend to use `booster` as the initcpio generator, and I've set that as default after https://github.com/7Ji/orangepi5-archlinuxarm/commit/a0be71252ec44e345df02095dfd8193a1e39ed36

**Comment by hronro** [comment]
I apologize for reaching out here. I have reinstalled the operating system using the latest 5_plus.img, and everything is functioning properly now.

Although I can execute `pacman -Syu linux-aarch64-7ji` successfully, it seems that the new kernel is not activated after restarting.

Upon inspecting `/boot/extlinux/extlinux.conf`, I noticed that the new kernel is not listed there either.

Do you have any suggestions for me?

**Comment by 7Ji** [comment]
You need to modify the config by yourself, there'no automcated mechanism to update the extlinux.conf

**Comment by hronro** [comment]
Hi @7Ji, thanks for your quick response.

I checked my `/boot` directory and found it seems some files are missing.

![CleanShot 2024-05-17 at 17 31 26@2x](https://github.com/7Ji/orangepi5-archlinuxarm/assets/15059605/26858d5f-847c-4f4c-b9d9-4f77124a7149)

There is only one img file in `/boot`. The `/booster-linux-aarch64-rockchip-rk3588-bsp5.10-orangepi-git.img` and the img file for the `linux-aarch64-7ji` kernel are missing.

**Comment by 7Ji** [comment]
You now only have `linux-aarch64-rockchip-rk3588-bsp5.10-orangepi` installed, the others are not "missing", but rather "not removed" when you uninstall the corresponding kernel. Install them again if you want to use them.

**Comment by hronro** [comment]
I didn't uninstall `linux-aarch64-7ji`.

**Comment by 7Ji** [comment]
Then run `/usr/lib/booster/regenerate_images` to regenerate all booster images
