### ISSUE TITLE
7Ji will you help OrangePi-3b Users

### ISSUE THREAD

**Issue by defencedog** [7Ji/orangepi5-archlinuxarm#48]
Thsi repo is great as far as GPU related stuff is involved. I am requesting you to please make OPi-3b image as well. Or at least provide some way for GPU VPU acceleration in KODI or JellyFin.

Best regards,

**Comment by 7Ji** [comment]
Sorry but I don't have a -3b board, my policy is that I only provide images for devices I personally own and can verify periodically. But I'm thinking about splitting the generic parts of this project and my another project amlogic-s9xxx-archlinuxarm to a common Arch-derive builder so others could easily implement their own. (They have A LOT in common, but I never had time to split them)

Another point is that you can start maintaining your own -3b kernel package and submit it to https://github.com/7Ji/archrepo later.
